[package]
name = "mips-debugger"
version = "0.1.0"
authors = ["Mark Drobnak <mark.drobnak@gmail.com>"]
edition = "2018"

[dependencies]
colored = "2.0"
env_logger = "0.7"
log = "0.4"
mips-r2k = { path = "../mips-r2k" }
mips-simulator = { path = "../mips-simulator" }
structopt = "0.3"
